# nixy listening port
port = "6000"

# optional X-Proxy header name
xproxy = "hostname"

# marathon api
marathon = "http://localhost:8080"

# nginx
nginx_config = "/etc/nginx/nginx.conf"
nginx_template = "/etc/nginx/nginx.tmpl"
nginx_cmd = "nginx"

# statsd settings
statsd = "localhost:8125" # optional if you want to graph req/s per app
